### ISSUE TITLE
Is the block reachable?

### ISSUE THREAD

**Issue by guma44** [ENCODE-DCC/hic-pipeline#100]
Hi,
I might be not spotting something. I have question to the line here: https://github.com/ENCODE-DCC/hic-pipeline/blob/dev/hic.wdl#L54. It contains the reference to `ligation_site_regex` but it is accessed in the block where `ligation_site_regex` is not defined (checked in if). Thus, when I pass `ligation_site_regex` to the pipeline `ligation_site` is not calculated causing an error in Cromwell.

**Comment by paul-sud** [comment]
You are right, let me update the WDL.

**Comment by paul-sud** [comment]
Ok I have updated dev (fixed in https://github.com/ENCODE-DCC/hic-pipeline/pull/101), please pull and try again.

**Comment by guma44** [comment]
Thanks a lot!
