### ISSUE TITLE
Running into error using bwa-mem2

### ISSUE THREAD

**Issue by HenryCWong** [ENCODE-DCC/hic-pipeline#106]
I managed to get bwa-mem2 on the a modified version of the docker container in this repo and ran it with a modified version of hic.wdl file (just changed bwa to bwa-mem2). However I am running into an error on the "create_hic" task. 

```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/storage1/fs1/dspencer/Active/wongh/hic3/hic2/hic-pipeline/hic/36ac2820-10fe-4650-a1a5-9cdd32a858d9/call-create_hic_with_chrom_sizes/shard-0/attempt-2/tmp.3597dba1
Unable to read merged nodups index
tmpdir=/storage1/fs1/dspencer/Active/wongh/hic3/hic2/hic-pipeline/hic/36ac2820-10fe-4650-a1a5-9cdd32a858d9/call-create_hic_with_chrom_sizes/shard-0/attempt-2/tmp.3597dba1
Unable to read merged nodups index
```

I know you guys aren't supporting bwa-mem2 but i was hoping you guys had some advice on where to start with debugging this. Bwa-mem2 claims to not to have changed the format but that's clearly not the case.

**Comment by paul-sud** [comment]
The `create_hic` task doesn't invoke BWA. To me this seems like the merged nodups index was not decompressed before running Juicer Tools `pre`. Which is a little odd because the pipeline takes care of the decompression already: https://github.com/ENCODE-DCC/hic-pipeline/blob/03ee3fa8f514c862b29ef6115a4fb7a19628f492/hic.wdl#L578

Maybe you edited the WDL or are using an older pipeline version?

**Comment by HenryCWong** [comment]
That line of code seems to be in the hic.wdl file. Is there anyway I can output what file is being passed in? 
I suspect bwa-mem2 might be isn't generating a file that the pipeline needs so an empty file is being passed throughout the pipeline.

**Comment by paul-sud** [comment]
The merged nodups index is not created by BWA, it is created with an Awk script then gzipped: https://github.com/ENCODE-DCC/hic-pipeline/blob/03ee3fa8f514c862b29ef6115a4fb7a19628f492/hic.wdl#L490

I would check to make sure you have that file.

**Comment by HenryCWong** [comment]
Yep that line is in the hic.wdl file. The initial bam file seems to come from the align task which uses bwa. Which then modifies and uses the bam file through a series of other tasks before it gets to hic_create. 
The only change I've made is changing bwa to bwa-mem2 in the align task. I've switched it back to bwa, ran the pipeline, and it worked fine.

**Comment by paul-sud** [comment]
I see. It's hard for me to say what exactly the issue is, I'm not familiar with bwa mem2. You will probably need to do some poking on the bams at various steps to see if there is anything going wrong. You probably want to look at the merged nodups file too since this might be causing the problems with the index.

**Comment by HenryCWong** [comment]
The merged node up file looks like this
`-,0,,0` 

while a successful run with the tests looks like 

```
chrIII-chrIII,0,0,13142316
chrIII-chrM,0,13142316,8182
chrM-chrM,0,13150498,174654
```
So something is screwing up. I'm going to just look through all the files and see where things start going south.

**Comment by HenryCWong** [comment]
I'm looked at the aligned.bam files that come out of the align task. Using regular bwa the file size is 44MB while the use of bwa-mem2 is 63 bytes. I know bwa-mem2 files sizes are supposed to be more compressed but I don't think it's at that degree. 

My theory is that some of the flags from bwa were not inherited into bwa-mem2. 

In that sense what does the `-SP5M ` flag do? I can't find it in the man page for bwa.

**Comment by paul-sud** [comment]
63 bytes is probably an empty file. You can see an explanation of the flags here: https://data.4dnucleome.org/resources/data-analysis/hi_c-processing-pipeline#alignment

**Comment by HenryCWong** [comment]
Thanks for the link! It looks like the people who made bwa-mem2 didn't implement the `-5` flag so as it stands, I don't think it's possible to run Hi-C data on bwa-mem2. I'll throw up an issue over there and see if they will implement it. If they do I'll try to update this thread, but for now I'll close it. 
Thanks for your help!
