### ISSUE TITLE
fail to locate the index files

### ISSUE THREAD

**Issue by HenryCWong** [ENCODE-DCC/hic-pipeline#107]
I ran an .fa file to get a sequence and then ran `bwa mem` to get all the index files. I then tar'd all of them into `all_sequences.tar` and then used pigz to zip up it up. 

So my director for all my index files look like this
```
all_sequences.fa.gz	 all_sequences.fa.gz.ann  all_sequences.fa.gz.pac  all_sequences.tar
all_sequences.fa.gz.amb  all_sequences.fa.gz.bwt  all_sequences.fa.gz.sa   all_sequences.tar.gz
```

I then run `caper run hic.wdl -i /storage1/fs1/dspencer/Active/wongh/hic-pipeline/input.json --backend-file /storage1/fs1/dspencer/Active/wongh/hic-pipeline/lsf.backend.conf `

To which I get the following error message after the align task fails. 

**Error Message** 
```
[E::bwa_idx_load_from_disk] fail to locate the index files
[E::bwa_idx_load_from_disk] fail to locate the index files

```

Everything seems to work on the test data. The only difference is the input file. 

**input file**
```
{
  "hic.assembly_name": "hg38",
  "hic.chrsz": "/storage1/fs1/dspencer/Active/wongh/hg38/hg38.sizes.tsv",
  "hic.fastq": [
    [
      {
        "read_1": "/storage1/fs1/dspencer/Active/wongh/sequences/Spencer_O624_HiC_RG_020221_IDT_10nt_UDI_i7_102_IDT_10nt_UDI_i5_293_AACCTAGTGC_TTCAGTATCG_S22_L001_R1_001.fastq.gz",
        "read_2": "/storage1/fs1/dspencer/Active/wongh/sequences/Spencer_O624_HiC_RG_020221_IDT_10nt_UDI_i7_102_IDT_10nt_UDI_i5_293_AACCTAGTGC_TTCAGTATCG_S22_L001_R2_001.fastq.gz"
      }
    ]
  ],
  "hic.no_call_loops": true,
  "hic.no_call_tads": true, 
  "hic.reference_index": "/storage1/fs1/dspencer/Active/wongh/indexes2/all_sequences.tar.gz",
  "hic.restriction_enzymes": [
    "MboI"
  ],
  "hic.restriction_sites": "/storage1/fs1/dspencer/Active/wongh/hg38/hg38_MboI.txt"
}
```

Is there a specific format I should be following for the index files?

**Comment by paul-sud** [comment]
There are the files I see when I extract the BWA index tar we use for the tests: https://github.com/ENCODE-DCC/hic-pipeline/blob/dev/tests/data/ce10_selected.tar.gz

```
ce10_selected.fa.gz
ce10_selected.fa.gz.amb
ce10_selected.fa.gz.ann
ce10_selected.fa.gz.bwt
ce10_selected.fa.gz.pac
ce10_selected.fa.gz.sa
```
Looks like you have all the six files there, although maybe there is something odd about the tar structure. When extracting it you should end up with the six files in the directory you extract from. Also I'm not familiar with `pigz` but the pipeline uses `gzip`, there could be some incompatibility that causes this issue.

When passing the tarball to BWA the pipeline does some manipulations to set the path to the reference fasta for BWA, see https://github.com/ENCODE-DCC/hic-pipeline/blob/03ee3fa8f514c862b29ef6115a4fb7a19628f492/hic.wdl#L278

Perhaps there is something finicky about this process, although it's worked fine so far when using the Docker image. It might be worth manually stepping through the Bash commands to see if it works.

**Comment by HenryCWong** [comment]
Where would the script make the reference folder? I can't seem to find it in the hic/{id}

**Comment by paul-sud** [comment]
Creating the BWA reference tar is not part of the pipeline, you need to do it manually or use a premade tar.

**Comment by HenryCWong** [comment]
I was more asking where the reference folder from the `mkdir reference` folder is put. I can't seem to find it after running the hic.wdl file. 
I also made a .tar and then recently used gzip instead of pigz6 on .fa files and I still get the same error.

**Comment by paul-sud** [comment]
The reference folder is created wherever the working directory of the task is. So for every `hic.align` task a new `reference` folder will be created.

**Comment by HenryCWong** [comment]
Thanks, found it in the hic file, somehow missed it. It looks like I can't have paths in my tar file. My tar file had folders in and I think that broke the pipeline because it expected to find the index files right after "reference". Thankfully paths is an easy fix in the .tar.gz file. Thanks for all the help again!
