### ISSUE TITLE
hic-pipeline seems have a bug 

### ISSUE THREAD

**Issue by tanzhengtang** [ENCODE-DCC/hic-pipeline#120]
**Describe the bug**
I try to run hic pipeline(v1.0.0 and v1.2.1),it always suddenly stopped at "python3: can't find '__main__' module in "

**OS/Platform**
- OS/Platform: Ubuntu 18.04
- Conda version: v4.10.3.
- Pipeline version: v1.0.0 and v1.2.1
- Caper version: v1.6.3

**Caper configuration file**
backend=local
local-hash-strat=path+modtime
local-loc-dir=/home/tang/tools/caper/cache
cromwell=/home/tang/.caper/cromwell_jar/cromwell-59.jar
womtool=/home/tang/.caper/womtool_jar/womtool-59.jar

**Input JSON file**
{
  "hic.assembly_name":"GRCh38",
  "hic.chrsz":"/home/tang/tools/encode_ref/GRCh38_EBV.chrom.sizes.tsv",
  "hic.fastq":[
      [
		  {
		"read_1":"/home/tang/HepG2/Omics_data/Hi-C/rep1/SRR5941004_R1.fastq.gz",
        "read_2":"/home/tang/HepG2/Omics_data/Hi-C/rep1/SRR5941004_R2.fastq.gz"
		  }
      ],
	  [
		  {
		 "read_1":"/home/tang/HepG2/Omics_data/Hi-C/rep2/SRR5941003_R1.fastq.gz",
		"read_2":"/home/tang/HepG2/Omics_data/Hi-C/rep2/SRR5941003_R2.fastq.gz"
		  }
    ]
  ],
  "hic.reference_index":"/home/tang/tools/encode_ref/ENCFF643CGH.tar.gz",
  "hic.restriction_enzymes":["none"]
}

**Error log**
* Started troubleshooting workflow: id=35a81bbd-b610-44ff-b866-3a4d445b2fbf, status=Failed
* Found failures JSON object.
[
    {
        "message": "Workflow failed",
        "causedBy": [
            {
                "message": "Job hic.normalize_assembly_name:NA:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                "causedBy": []
            },
            {
                "causedBy": [],
                "message": "Job hic.get_ligation_site_regex:NA:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ]
    }
]
==== NAME=hic.get_ligation_site_regex, STATUS=Failed, PARENT=
SHARD_IDX=-1, RC=1, JOB_ID=1686
START=2021-09-09T04:32:06.576Z, END=2021-09-09T04:32:13.546Z
STDOUT=/home/tang/HepG2/Omics_data/Hi-C/hic/35a81bbd-b610-44ff-b866-3a4d445b2fbf/call-get_ligation_site_regex/attempt-2/execution/stdout
STDERR=/home/tang/HepG2/Omics_data/Hi-C/hic/35a81bbd-b610-44ff-b866-3a4d445b2fbf/call-get_ligation_site_regex/attempt-2/execution/stderr
STDERR_CONTENTS=
/home/tang/miniconda3/envs/encode-chip-seq-pipeline/bin/python3: can't find '__main__' module in ''

**Comment by leepc12** [comment]
You tried to run the hic-pipeline inside chip-seq-pipeline's conda environment.
hic-pipeline is designed to work with a docker container (not Conda).

Please install docker on your computer and try with `caper run/submit ... --docker`.
We recommend to run it on Google Cloud Platform.

Please see this document for details
https://github.com/ENCODE-DCC/caper/tree/master/scripts/gcp_caper_server

**Comment by tanzhengtang** [comment]
Thanks!
I will run it again as you said.

**Comment by paul-sud** [comment]
Hi @tanzhengtang , were you able to resolve this issue?

**Comment by tanzhengtang** [comment]
Hi,i have run this pipeline as leepc12 said,it didn't work.
our server do not install the gpu driver is a possible reason.

**Comment by paul-sud** [comment]
Cromwell only supports GPUs on Google Cloud AFAIK. You can disable the GPU steps in the pipeline by setting `"hic.no_call_loops": true` and `"hic.no_delta": true` in your input, then you should be able to run without a GPU on any backend.

In any case, sounds like this particular issue is resolved, I'm going to close this issue. Feel free to open another one though if you have any other problems or questions.
