### ISSUE TITLE
Error running example on local computer

### ISSUE THREAD

**Issue by andreevakali** [ENCODE-DCC/hic-pipeline#54]
Hello,

I am attempting to learn to use the hic-pipeline on a local Ubuntu 18.04 virtual machine.  I am attempting to run it with the tutorial data.

Platform/OS: Ubuntu 18.04 VM (using Ubuntu Multipass on Windows 10 Pro)

Python: 3.6.9

Singularity: 2.4.2-dist

Docker: 19.03.8, build afacb8b7f0

Java: 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

Caper: 0.8.0 (Initialized for 'local')

The tutorial options for '--use-docker' and '--use-singularity' are unrecognized commands from caper.

Steps taken to run hic-pipeline:
cd hic-pipeline
INPUT=examples/template_one.json 
PIPELINE_METADATA=metadata.json
sudo caper run workflow/main_workflow/hic.wdl -i ${INPUT} -m ${PIPELINE_METADATA}

The following error was written to stderr:
/opt/scripts/common/countligations.sh: No such file or directory
samtools: command not found
bwa: command not found

The output is attached:
[hic_pipeline_error_output.txt](https://github.com/ENCODE-DCC/hic-pipeline/files/4418238/hic_pipeline_error_output.txt)

Thank you,
Kalina

**Comment by leepc12** [comment]
'--use-docker' has been deprecated. Use `--docker'. It can work as a flag too.

**Comment by andreevakali** [comment]
Thank you for the rapid reply!

I have updated my call to run the pipeline from '--use-docker' to '--docker'.  

I ran the pipeline again using the provided example for hic-pipeline.

The hic-pipeline run proceeds much further and no longer produces an output to stderr.  However it still states that it failed at the end of the run.

One of the final statements was that it wrote metadata to metadata.json, but no metadata.json file exists at the indicated directory location.

It produced the following screen output:
[hic_pipeline_error_output2.txt](https://github.com/ENCODE-DCC/hic-pipeline/files/4422354/hic_pipeline_error_output2.txt)

Thank you,
Kalina

**Comment by leepc12** [comment]
`cd` into Cromwell's execution directory.
```bash
$ cd /home/ubuntu/hic-pipeline/hic/555db210-383f-4155-b35b-211d9ddb6a73/call-arrowhead/execution
```

Please post contents of two files `stdout` and `stderr`.
Also check if there is any other meaningful log files helpful for debugging. (e.g. `*.log`, `*.txt', ...)

**Comment by andreevakali** [comment]
Thank you for all the support!

I have attached the stderr, stdout, stderr.background, stdout.background file contents below:
[stderr and stdout content.txt.txt](https://github.com/ENCODE-DCC/hic-pipeline/files/4422698/stderr.and.stdout.content.txt.txt)

I have also attached the output of the search of  *.log and *.txt :
[text and log files.txt.txt](https://github.com/ENCODE-DCC/hic-pipeline/files/4422775/text.and.log.files.txt.txt)

Thank you,
Kalina

**Comment by leepc12** [comment]
```
ubuntu@hic-pipeline2:~/hic-pipeline/hic/555db210-383f-4155-b35b-211d9ddb6a73/call-arrowhead/execution$ cat stderr
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell-executions/hic/555db210-383f-4155-b35b-211d9ddb6a73/call-arrowhead/tmp.a33c6e98
Warning: Hi-C map is too sparse to find many domains via Arrowhead.
Exiting. To disable sparsity check, use the --ignore_sparsity flag.

ubuntu@hic-pipeline2:~/hic-pipeline/hic/555db210-383f-4155-b35b-211d9ddb6a73/call-arrowhead/execution$ cat stdout
WARN [2020-04-02T14:51:02,675]  [Globals.java:138] [main]  Development mode is enabled
Reading file: /cromwell-executions/hic/555db210-383f-4155-b35b-211d9ddb6a73/call-arrowhead/inputs/241354813/inter_30.hic
Using 2 CPU threads
```

It looks like `arrowhead` task failed to produce outputs?
```
Warning: Hi-C map is too sparse to find many domains via Arrowhead.
Exiting. To disable sparsity check, use the --ignore_sparsity flag.
ln: failed to access '/cromwell-executions/hic/555db210-383f-4155-b35b-211d9ddb6a73/call-arrowhead/execution/contact_domains/*.bedpe': No such file or directory
```

Did you use pipeline's test sample or your own data?

**Comment by andreevakali** [comment]
Yes, there were no arrowhead outputs.
I am using the pipeline's test sample.

**Comment by paul-sud** [comment]
Hi Kalina,

Sorry for joining this thread late. Arrowhead requires Hi-C maps to contain enough contacts to work. The test fastqs are not big enough to run the pipeline all the way through loop calling.

If you want to verify that arrowhead works, you can run the arrowhead test with this WDL and input JSON:
https://github.com/ENCODE-DCC/hic-pipeline/blob/dev/test/test_task/test_arrowhead.json
https://github.com/ENCODE-DCC/hic-pipeline/blob/dev/test/test_task/test_arrowhead.wdl

Hope that helps, please let me know if you have any questions.

Best,

Paul

**Comment by andreevakali** [comment]
Thank you so much for the assistance!

I did the following steps:

A)  I restarted the Ubuntu virtual machine that I am using, as I noticed that the memory usage after running hic-pipeline did not return to it's previous level.

B)  I renamed my previous checkout of hic-pipeline from Github, and checked out a fresh copy to my Ubuntu virtual machine.

C)  I copied both specified files to the hic-pipeline directory:
    /home/ubuntu/hic-pipeline/test_arrowhead.json
    /home/ubuntu/hic-pipeline/test_arrowhead.wdl

D)  In a previous attempt, I continued getting errors that "../../hic.wdl" was not found when attempting to run the pipeline.  

I had noted that hic.wdl is in the base hic-pipeline directory.

I changed the specified file in test_arrowhead.wdl from "../../hic.wdl" to "hic.wdl".

E)  I executed the following commands to run the pipeline:

$ INPUT=test_arrowhead.json 
$ PIPELINE_METADATA=metadata.json
$ caper run workflow/main_workflow/test_arrowhead.wdl --docker -i ${INPUT} -m ${PIPELINE_METADATA}

Result:

After getting the pipeline to run with the steps as described above, I got the following error in stderr:

/home/ubuntu/hic-pipeline/test_arrowhead/1762b333-67f2-4336-bf75-d3e800f8c075/call-test_arrowhead_task/attempt-2/execution/script: line 22: juicer_tools: command not found

Any advice?  Is there any other example that I should use to evaluate the hic-pipeline?  Did I run the pipeline in the correct manner?

Thank you again for all the assistance!
Kalina

**Comment by paul-sud** [comment]
I tested this and was able to replicate your error. I think you need to additionally specify a docker image tag like so (scroll right to see the full command):
```
caper run test/test_task/test_arrowhead.wdl -i test/test_task/test_arrowhead.json -b local --docker quay.io/encode-dcc/hic-pipeline:template
```

Otherwise, the tasks will run outside of any containers and juicer_tools will not be found. The `--docker` flag without any image following will only work if the WDL specifies a `#CAPER docker` pragma, which the test WDLs do not.

To be safe, I'd make sure your docker image is up to date by running `docker pull quay.io/encode-dcc/hic-pipeline:template` as well.

Hope that helps,

Paul

**Comment by andreevakali** [comment]
Thank you, Paul and Jin!

I appreciate your help with all the issues with running the pipeline.

I was able to run the hic-pipeline for testing the arrowhead algorithm.  A metadata.json file and 5000_blocks.bedpe file was generated.

Thank you,
Kalina
