### ISSUE TITLE
Restriction sites not available 

### ISSUE THREAD

**Issue by guma44** [ENCODE-DCC/hic-pipeline#95]
Hi,
The links in the documentation to the restriction enzyme sites are broken. From where I could download the sites? Or should I create an account?
Thanks a lot!
Rafal

**Comment by paul-sud** [comment]
Hi Rafal, those files were not yet publicly available, you should be able to see and download them now. Sorry about that!.

**Comment by guma44** [comment]
@paul-sud  Hi, indeed they are working now. Thanks a lot!
